### ISSUE TITLE
Hidden Tech links broken

### ISSUE THREAD

**Issue by alexroseb** [izgeri/western-mass-tech#8]
In western-mass-tech/resources.md, the links to Hidden Tech work but the links to the mailing list on their site don't work (there are actually two different links that are designated "sign up" but neither works). Is there a newer updated list? If not, it should be noted next to the links that the site is a resource but the mailing list isn't. 
Thanks!

**Comment by izgeri** [comment]
Thanks @abrenon, I just sent an email to the webmaster for the site to ask them to address this. I'll update here when I find out more. I'll also add a note to the resource page for now.

**Comment by izgeri** [comment]
From the HT webmaster:

> We are moving web servers and from Joomla to Wordpress, SO will be fixed
> If you have someone you want to add, email the webmaster at webmaster@hidden-tech.net
